name       : perl-datetime-calendar-julian
version    : '0.107'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/W/WY/WYANT/DateTime-Calendar-Julian-0.107.tar.gz : fcb2b424844bb13bcad46b1c7aa239b5a09bab2556f53bd1f27fad90c260d33d
homepage   : https://metacpan.org/pod/DateTime::Calendar::Julian
license    : Artistic-2.0
component  : programming.perl
summary    : DateTime::Calendar::Julian - Dates in the Julian calendar
description: |
    DateTime::Calendar::Julian implements the Julian Calendar. This module implements all methods of DateTime; see the DateTime(3) manpage for all methods.
builddeps  :
    - perl-datetime
rundeps    :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
