name       : perl-datetime-calendar-julian
version    : '0.106'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/W/WY/WYANT/DateTime-Calendar-Julian-0.106.tar.gz : faafa769a5e70ff1b584f6e2ef16561588d88c74bc336bddc1aa00f3381ba86c
license    : Artistic-2.0
component  : programming.perl
summary    : Dates in the Julian calendar
description: |
    Dates in the Julian calendar
builddeps  :
    - perl-datetime
rundeps    :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
