name       : perl-datetime-calendar-julian
version    : 0.04
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PI/PIJLL/DateTime-Calendar-Julian-0.04.tar.gz : bb5968ad18bcd0772d2c311cd2deb23b777475ea05aa1099688247cd27a5000e
license    : Artistic-2.0
component  : programming.perl
summary    : Dates in the Julian calendar
description: |
    Dates in the Julian calendar
builddeps  :
    - perl-datetime
rundeps    :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
